version: "3.9"

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: unless-stopped
    tty: true
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=foobared

volumes:
  redis-data:
    driver: local